
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actionable notifications skill. Did it work?", "event": "actionable.skill.test"}'
  
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

##############################################
#                   Alexa                    #
##############################################
alexa:
  smart_home:

my:

input_number:
  my_number:
    name: My Number
    initial: 0
    min: 0
    max: 100
    step: 1

input_datetime:
  my_time:
    has_date: true
    has_time: true

# Example configuration.yaml entry
ifttt:
  key: 'ia1tOn3Cmt6h-5oYxRldJIGZOEIR8d9X1WKYmrVKDUK'

aws:
  credentials:
    - name: cuenta_AWS
  notify:
    # use the first credential defined in aws integration by default
    - service: lambda
      region_name: eu-west-1

